### ISSUE TITLE
Library tracing

### ISSUE THREAD

**Issue by jpmonettas** [jpmonettas/flow-storm#3]
Experiment with ways to trace functions that are outside our main project. 

In clojure we can maybe trace vars by instrumenting its src with clojure.repl/source-fn ?

**Comment by ingesolvoll** [comment]
This feature would be very useful to me. Both for understanding 3rd party deps, and for working in multi-project environments.

Maybe an API like this? `(flow-storm/trace-var 'clojure.core.cache/clear-soft-cache!)`

**Comment by jpmonettas** [comment]
@ingesolvoll this was implemented as `flow-storm.api/trace-var` and `flow-storm.api/untrace-var`, take a look at
https://github.com/jpmonettas/flow-storm#instrumenting-library-code-with-trace-var

Cheers!

**Comment by ingesolvoll** [comment]
@jpmonettas 

Nice!

Looks like this feature requires REPL for CLJS? You can't really do `in-ns` in a source file, or am I wrong?

**Comment by jpmonettas** [comment]
@ingesolvoll yeah it is intended for the repl.
