### ISSUE TITLE
Error running from CLJS in browser

### ISSUE THREAD

**Issue by ingesolvoll** [jpmonettas/flow-storm#6]
I tried requiring and running `(fs-api/connect)` from my browser CLJS app. 

Got this error:
`/js/main.out/flow_storm/api.cljs No such var: sente/make-channel-socket-client!`

I wasn't sure if it's supposed to work from the browser, or if it has been tested much in that env. 

My first thought seeing this was that it sounds like a macro created some code that lacks require statement in the calling namespace.

**Comment by jpmonettas** [comment]
Hi @ingesolvoll , thanks for reporting that.

Yes, it has been tested with the browsers and it should work fine.

Does your project contains a version of sente that is maybe conflicting with the version flow-storm is using?

Requiring `flow-storm.api` should load `flow-storm.tracer` who then loads `taoensso.sente`.

There aren't any macros involved in `fsa-api/connect`, it is just a function that ends up calling `taoensso.sente/make-channel-socket-client!` to create the websocket connection to the debugger.

Maybe if you can share a repo I can help you with that.

**Comment by ingesolvoll** [comment]
@jpmonettas Thanks for the quick reply! You were right about the version conflict, and it was easy to fix. This was caused by my project already declaring 0.14.0 for sente.

I now have the tool running nicely, and I already found a previously unknown bug in my code that was easy to see by stepping through a randomly selected form just to test your tool. 

Very nice tool, impressed so far.
