### ISSUE TITLE
CSRF Warning

### ISSUE THREAD

**Issue by ingesolvoll** [jpmonettas/flow-storm#8]
On connecting to the debugger, the supporting library causes this warning in the browser app:

`WARN [taoensso.sente:1598] - WARNING: no CSRF token provided. Connections will FAIL if server-side CSRF check is enabled (as it is by default).`

There is no clean way to get rid of the warning, but from reading the sente code, I think the warning will go away if you pass in a non-empty string as CSRF-token. I'm assuming the server is configured to ignore CSRF anyway, so that should work.

**Comment by jpmonettas** [comment]
Thanks again @ingesolvoll !
